<!DOCTYPE html>
<html>
<head>
	<title>test</title>
	<meta name="keywords" content="">
	<meta name="description" content="">
	
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<link href="http://g.alicdn.com/sj/dpl/1.4.3/css/sui.min.css" rel="stylesheet">
	<!-- <link type="text/css" rel="stylesheet" href="<?php echo $this->getStaticUrl();?>/css/myui.css" media="all"> -->
	<link type="text/css" rel="stylesheet" href="<?php echo $this->getStaticUrl();?>/css/main.css" media="all">
	
	<script type="text/javascript" src="<?php echo $this->getStaticUrl();?>/js/head.js"></script>
    <script type="text/javascript">
    	/*
	    head.test((head.browser.ie && head.browser.version <= 8),
				  [], 
				  ["<?php echo $this->getStaticUrl();?>/js/ie9.js"],
				  function() {
				  }
		);
	*/
    	head.js({libs: "<?php echo $this->getStaticUrl();?>/js/dzg_lib.min.js?ver=11"},
    			"<?php echo $this->getStaticUrl();?>/js/knockout-3.3.0.js",
	    		"<?php echo $this->getStaticUrl();?>/js/script.js",
	    		"<?php echo $this->getStaticUrl();?>/js/myui.js",
	    		"http://g.alicdn.com/sj/dpl/1.4.3/js/sui.min.js");
    </script>
</head>

<body id="<?php echo $this->getBodyId();?>">
<!-- #header -->
<div id="header">
	<div id="header-box">
		<div id="logo">
			<a href="#"><img alt="大掌柜_自动橱窗" src="<?php echo $this->getStaticUrl();?>/i/logo.png" /></a>
		</div>
		<ul id="header-menu">
			<li><span><?php echo "您好，".$this->getUserName();?></span></li>
			<li><a href="<?php echo Common::getUrl('core/index/logout');?>">[退出]</a></li>
		</ul>
	</div>
</div>
<!-- end of #header -->

<div id="wrap">
	<!-- #container -->
	<div id="container">
		<!-- menu --><?php echo $this->getBlockHtml('core/page_menu')?><!-- end of menu -->
		<!-- content --><?php echo $this->getBlockHtml('content');?><!-- end of content -->
	</div><!-- end of #container -->
</div><!-- #wrap -->
<div class="clear"></div>
<!-- #footer -->
<div id="footer">
	<div class="copyright">© 2013 xxxx 版权所有</div>
</div>
<!-- end of #footer -->
<script  type="text/javascript">
    var baseUrl = "<?php echo Common::getBaseUrl();?>";
	<?php 
		$moduleJs = Util::factory("js")->getJsUrl();
		if (!empty($moduleJs)){
	?>
	head.js("<?php echo  $this->getStaticUrl().'/js/'.$moduleJs;?>");
	//head.load("http://testzh.testzh.com/static/js/tools/mobiledetail/index.js");
	<?php 
		}
	?>
</script>
</body>
</html>