<!DOCTYPE html>
<html>
<head>
	<title>WQUI</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<link href="http://g.tbcdn.cn/sj/wqui/1.0.0/css/sui.min.css" rel="stylesheet">
	<script type="text/javascript" src="http://g.tbcdn.cn/sj/lib/jquery/dist/jquery.min.js"></script>
	<script type="text/javascript" src="http://g.tbcdn.cn/sj/wqui/1.0.0/js/sui.min.js"></script>
</head>

<body>
	<p>面包屑代码</p>
    <ul class="sui-breadcrumb">
	    <li><a href="#">首页</a></li>
	    <li><a href="#">手机数码、电脑办公</a></li>
	    <li class="active">智能手机</li>
    </ul>
    <hr>
    <p>提示消息代码</p>
	<div class="sui-msg msg-large msg-block msg-success">
	    <div class="msg-con">新的待办事项”晚上9点拿夜宵”创建成功！</div>
	    <s class="msg-icon"></s>
    </div>
    <hr>
	<p>表单代码</p>
	<form class="sui-form form-horizontal sui-validate" action="" method="post" id="servingForm">
	    <div class="control-group">
	        <label class="control-label">名称：</label>
	        <div class="controls">
	            <input class="input-xlarge" type='text' data-rules="required|minlength=2|maxlength=50"
	            />
	        </div>
	    </div>
	    <div class="control-group">
	        <label class="control-label">时间：</label>
	        <div class="controls">
	            <select class="input-medium " name='month' data-rules='required'>
	                <option value="1">
	                    1
	                </option>
	                <option value="2">
	                    2
	                </option>
	                <option value="3">
	                    3
	                </option>
	                <option value="4">
	                    4
	                </option>
	                <option value="5">
	                    5
	                </option>
	                <option value="6">
	                    6
	                </option>
	                <option value="7">
	                    8
	                </option>
	                <option value="8">
	                    9
	                </option>
	                <option value="9">
	                    9
	                </option>
	                <option value="10">
	                    10
	                </option>
	                <option value="11">
	                    11
	                </option>
	                <option value="12">
	                    12
	                </option>
	            </select>
	            月
	            <select class="input-medium " name='date' data-rules='required'>
	                <option value="1">
	                    1
	                </option>
	                <option value="2">
	                    2
	                </option>
	                <option value="3">
	                    3
	                </option>
	                <option value="4">
	                    4
	                </option>
	                <option value="5">
	                    5
	                </option>
	                <option value="6">
	                    6
	                </option>
	                <option value="7">
	                    8
	                </option>
	                <option value="8">
	                    9
	                </option>
	                <option value="9">
	                    9
	                </option>
	                <option value="10">
	                    10
	                </option>
	                <option value="11">
	                    11
	                </option>
	                <option value="12">
	                    12
	                </option>
	            </select>
	            日
	        </div>
	    </div>
	    <div class="control-group">
	        <label class="control-label">
	            补充说明：
	        </label>
	        <div class="controls">
	            <textarea class='input-xlarge' data-rules='maxlength=100'>
	            </textarea>
	        </div>
	    </div>
	    <div class="control-group">
	        <div class="controls">
	            <button class="sui-btn btn-primary btn-xlarge">
	                创建待办事项
	            </button>
	        </div>
	    </div>
	</form>
	<hr>
	<p>下拉框</p>
	<span class="sui-dropdown dropdown-bordered select">
		<span class="dropdown-inner"><a id="drop12" role="button" data-toggle="dropdown" href="#" class="dropdown-toggle">
	  		<input value="hz" name="city" type="hidden"><i class="caret"></i><span>杭州</span></a>
			<ul id="menu12" role="menu" aria-labelledby="drop12" class="sui-dropdown-menu">
			  <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:void(0);" value="bj">北京</a></li>
			  <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:void(0);" value="sb">圣彼得堡</a></li>
			  <li role="presentation" class="active"><a role="menuitem" tabindex="-1" href="javascript:void(0);" value="hz">杭州</a></li>
			</ul>
		</span>
	</span>
	
	
</body>
</html>