    <form class="sui-form form-horizontal" action="" method="post" id="servingForm">
    <div class="control-group">
    <label class="control-label">名称：</label>
    <div class="controls">
    <input class="input-xlarge" type='text' />
    </div>
    </div>
    <div class="control-group">
    <label class="control-label">时间：</label>
    <div class="controls">
    <select class="input-medium " name='month'>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    <option value="6">6</option>
    <option value="7">8</option>
    <option value="8">9</option>
    <option value="9">9</option>
    <option value="10">10</option>
    <option value="11">11</option>
    <option value="12">12</option>
    </select>
    月
    <select class="input-medium " name='date'>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    <option value="6">6</option>
    <option value="7">8</option>
    <option value="8">9</option>
    <option value="9">9</option>
    <option value="10">10</option>
    <option value="11">11</option>
    <option value="12">12</option>
    </select>
    日
    </div>
    </div>
    <div class="control-group">
    <label class="control-label">补充说明：</label>
    <div class="controls">
    <textarea class='input-xlarge'></textarea>
    </div>
    </div>
    <div class="control-group">
    <div class="controls">
    <button class="sui-btn btn-primary btn-xlarge">创建待办事项</button>
    </div>
    </div>
    </form> 