<div id="content">
	<div class="box-title">
		<h1>必推荐的宝贝</h1>
	</div>

	<div class="breadcrumbs">
		<div class="primary">
			<div class="primary">
				<select value="按店铺分类选择商品" class="comboBox w-150">
					<option value="1_1">店铺分类1</option>
					<option value="1_2">店铺分类2</option>
					<option value="1_3">店铺分类3</option>
				</select>
				<select value="按淘宝分类选择商品" class="comboBox w-150">
					<option value="2_1">淘宝分类1</option>
					<option value="2_2">淘宝分类2</option>
					<option value="2_3">淘宝分类3</option>
				</select>
			</div>
			<div class="secondary">
				<a class="blueBtn-middle" onclick="search();" href="javascript:void(0);">搜索商品</a>
				<input type="text" name="keyword" value="输入关键字、商品ID或商家编号" class="input-text-middle w-240" style="border: 1px solid rgb(132, 191, 234);">
			</div>
		</div>
		<div class="secondary">
			<a title="列表模式" id="viewList" href="javascript:void(0);" class="select icon"></a>
			<a title="缩略图模式" id="viewThumb" href="javascript:void(0);" class="icon"></a>
		</div>
	</div>

	<div class="sequence">
		<ul>
			<li>
				<span>排序</span>	
			</li>
			<li>
				<a href="javascript:void(0);" class="selected" id="list_time_desc">下架时间降序</a>
				<a href="javascript:void(0);" id="list_time_asc">下架时间升序</a>
				<a href="javascript:void(0);" id="list_num_desc">库存数量降序</a>
				<a href="javascript:void(0);" id="list_num_asc">库存数量升序</a>
			</li>
		</ul>
		<ul>
			<li>
				<span>每页显示</span>
			</li>
			<li>
				<select value="每页显示宝贝数量" class="comboBox w-30">
					<option value="20">20</option>
					<option value="40">40</option>
					<option value="60">60</option>
				</select>
			</li>
			<li>
				<span>个</span>
			</li>
		</ul>
		<ul>
			<li>
				<span>1/2</span>
			</li>
			<li>
				<a title="上一页" href="javascript:void(0);" class="icon prevpage">
					<span></span>
				</a>
				<a title="下一页" href="javascript:void(0);" class="icon nextpage">
					<span></span>
				</a>
			</li>
		</ul>
	</div>
	<div class="line-height-20">
	</div>
	<!-- products -->
	<div class="products">
		<div class="product">
				<div class="imageWrapper">
					<a class="image" href="javascript:void(0);">
						<img alt="" src="http://img01.taobaocdn.com/bao/uploaded/i1/19409025522304515/T1DchPFaVgXXXXXXXX_!!0-item_pic.jpg_60x60.jpg">
					</a>
				</div>
				<div class="info">
					<a target="_blank" href="http://item.taobao.com/item.htm?id=21539711519">2013新款夏装女装大码牛仔短裤女夏糖果色彩色短裤热裤休闲裤子潮</a>
					<span class="price">
						<i>39.00</i> 元
					</span>
				</div>
		</div>
		<div class="product">
				<div class="imageWrapper">
					<a class="image" href="javascript:void(0);">
						<img alt="" src="http://img01.taobaocdn.com/bao/uploaded/i1/19409025522304515/T1DchPFaVgXXXXXXXX_!!0-item_pic.jpg_60x60.jpg">
					</a>
				</div>
				<div class="info">
					<a target="_blank" href="http://item.taobao.com/item.htm?id=21539711519">2013新款夏装女装大码牛仔短裤女夏糖果色彩色短裤热裤休闲裤子潮</a>
					<span class="price">
						<i>39.00</i> 元
					</span>
				</div>
		</div>
		<div class="product">
				<div class="imageWrapper">
					<a class="image" href="javascript:void(0);">
						<img alt="" src="http://img01.taobaocdn.com/bao/uploaded/i1/19409025522304515/T1DchPFaVgXXXXXXXX_!!0-item_pic.jpg_60x60.jpg">
					</a>
				</div>
				<div class="info">
					<a target="_blank" href="http://item.taobao.com/item.htm?id=21539711519">2013新款夏装女装大码牛仔短裤女夏糖果色彩色短裤热裤休闲裤子潮</a>
					<span class="price">
						<i>39.00</i> 元
					</span>
				</div>
		</div>
		<div class="product">
				<div class="imageWrapper">
					<a class="image" href="javascript:void(0);">
						<img alt="" src="http://img01.taobaocdn.com/bao/uploaded/i1/19409025522304515/T1DchPFaVgXXXXXXXX_!!0-item_pic.jpg_60x60.jpg">
					</a>
				</div>
				<div class="info">
					<a target="_blank" href="http://item.taobao.com/item.htm?id=21539711519">2013新款夏装女装大码牛仔短裤女夏糖果色彩色短裤热裤休闲裤子潮</a>
					<span class="price">
						<i>39.00</i> 元
					</span>
				</div>
		</div>
	</div>
	<!-- end of products -->
	<div class="footerpaging">
		<ul>
			<li>
				<a title="上一页" href="javascript:void(0);" class="icon prevpage">
					<span></span>
				</a>
			</li>
			<li>
				<a title="第1页" href="javascript:void(0);" class="icon page_1">
					<span>1</span>
				</a>
			</li>
			<li>
				<a title="第2页" href="javascript:void(0);" class="icon page_2">
					<span>2</span>
				</a>
			</li>
			<li>
				<a title="第3页" href="javascript:void(0);" class="icon page_3">
					<span>3</span>
				</a>
			</li>
			<li>
				<a title="第4页" href="javascript:void(0);" class="icon page_4">
					<span>4</span>
				</a>
			</li>
			<li>
				<a title="第5页" href="javascript:void(0);" class="icon page_5">
					<span>5</span>
				</a>
			</li>
			<li>
				<a title="第6页" href="javascript:void(0);" class="icon page_6">
					<span>6</span>
				</a>
			</li>
			<li>
				<a title="第7页" href="javascript:void(0);" class="icon page_7">
					<span>7</span>
				</a>
			</li>
			<li>
				<a title="第8页" href="javascript:void(0);" class="icon page_8">
					<span>8</span>
				</a>
			</li>
			<li>
				<a title="下一页" href="javascript:void(0);" class="icon nextpage">
					<span></span>
				</a>
			</li>
		</ul>
	</div>
</div>
