<!-- #content -->
<div id="content">
	<div id="main">
		<div class="">
			<h1>
				<ul class="sui-breadcrumb">
					<li><a href="#">商品管理</a></li>
					<li><a href="#">手机详情</a></li>
				</ul>
			</h1>
		</div>
		<ul class="sui-nav nav-tabs nav-large">
			<li class="active"><a data-toggle="tab" data-bind="click:function(){search('ONSALE');}">出售中</a></li>
			<li><a data-toggle="tab" data-bind="click:function(){search('INSTOCK');}">仓库中</a></li>
			<li><a data-toggle="tab" >已生成</a></li>
		</ul>
		<div style="margin-top: -10px;" class="sui-form" id="deschide">
			<span class="sui-dropdown dropdown-bordered dropdown-large select">
				<span class="dropdown-inner">
					<a id="select" role="button" href="javascript:void(0);" data-toggle="dropdown" class="dropdown-toggle">
						<input value="" name="ocategory" type="hidden" onchange="oselectfunc(this.value)">
						<i class="caret"></i><span>全部</span>
					</a>
					<ul role="menu" aria-labelledby="drop4" class="sui-dropdown-menu ocategory" name="ocategory" style="max-height: 300px; overflow-y: auto;">
						<li role="presentation" class="active">
							<a role="menuitem" tabindex="-1" href="javascript:void(0);" value="bj">全部</a>
						</li>
					</ul>
				</span>
			</span>
			<div class="input-control control-right">
				<input style="margin-left: 5px; width: 180px" class="input-fat" type="search" name="q" id="q" value="" placeholder="关键字、商品链接、商品编码" data-inline="true" onkeypress="event.keyCode==13?mobiledetailM.search():'';">
				<i class="sui-icon icon-touch-magnifier"></i>
			</div>
			<button style="margin-left: 15px;" class="sui-btn btn-primary btn-large" data-bind="click:function(){ search();}">搜索</button>
			<div id="page" style="display: inline-block; float: right;"></div>
		</div>
		<div class="ui-sortable">
			<table class="sui-table table-bordered table-zebra ">
				<thead>
					<tr>
						<th style="width:18px;">
							<div class="center">
								<label class="checkbox-pretty inline checked" data-toggle="checkbox">
								<input type="checkbox" checked="checked"><span contenteditable="true"></span>
								</label>
							</div>
						</th>
						<th style="width: 52px;">主图</th>
						<th style="">标题</th>
						<th class="center" style="width: 90px;">状态</th>
						<th class="center" style="width: 80px;">操作</th>
					</tr>
				</thead>
				<tbody data-bind="template: {name:'mobiledetailTpl', foreach: items}">
					
				</tbody>
			</table>
		</div>
		<div class="clear"></div>
		<div class="my-page center" style="padding-bottom:1px; display:block;"></div>
	</div>
</div>
<!-- end of #content -->

<script type="text/x-jquery-tmpl" id="mobiledetailTpl">
<tr>
    <td>
        <div class="center">
            <label class="checkbox-pretty inline checked" data-toggle="checkbox">
            <input type="checkbox" checked="checked"><span contenteditable="true"></span>
            </label>
        </div>
    </td>
    <td>
        <div class="center">
            <a target='_blank' data-bind="attr: {href: 'http://item.taobao.com/item.htm?id='+num_iid}" ><img style="margin: 0; height:60px; width:60px;" data-bind="attr: {src: pic_url, title: title }"></a>
        </div>
    </td>
    <td><a target='_blank' data-bind="text:title,attr: {href: 'http://item.taobao.com/item.htm?id='+num_iid}"></a></td>
    <td class="center">
		<span class="sui-label label-success">已生成</span>
	</td>
    <td class="center"><a href="javascript:void(0);" class="sui-btn btn-primary">生成图文</a></td>
</tr>
</script>
