<!-- #content -->
<div id="content">
<div style="width:980px;">
	<div class="box-title">
		<h1>手机详情</h1>
	</div>
	<div class="myui-btn-group">
		<a class="myui-btn btn-xxlarge btn-primary" href="javascript:void();">出售中</a><a class="myui-btn btn-xxlarge" href="javascript:void();">仓库中</a>
	</div>
	<table class="myui-table table-bordered" style="border:1px solid #e6e6e6;">
	  <thead>
	    <tr>
	      <th colspan="5"> 
	        <label class="checkbox pull-left">
	          <input type="checkbox">订单编号：7867473872181848
	        </label><span class="pull-right">成交时间：2014-01-11 11:59</span>
	      </th>
	    </tr>
	  </thead>
	  <tbody>
	    <tr>
	      <td width="50%">
	        <div class="typographic"><img style="width:50px;height:50px;" src="http://img02.tbsandbox.com/bao/uploaded/i2/TB1mvOKXXXXXXb9XXXXXXXXXXXX_!!2-item_pic.png_50x50.jpg"><a href="#" class="block-text" style="width:200px;">包邮 正品玛姬儿压缩面膜无纺布纸膜100粒 送泡瓶面膜刷喷瓶 新款</a><span>1</span>
	        </div>
	      </td>
	      <td rowspan="1" class="center" width="11%">56.50</td>
	      <td rowspan="1" class="center" width="13%">
	        <ul class="unstyled">
	          <li>交易成功</li>
	          <li><a href="#">订单详情</a></li>
	          <li><a href="#">对方已评</a></li>
	        </ul>
	      </td>
	      <td rowspan="1" class="center" width="13%"><a href="#" class="btn">评价 </a></td>
	      <td rowspan="1" class="center" width="13%">
	        <ul class="unstyled">
	          <li><a href="#">删除</a></li>
	          <li><a href="#">标记</a></li>
	          <li><a href="#">分享</a></li>
	        </ul>
	      </td>
	    </tr>
	    <tr>
	      <td width="50%">
	        <div class="typographic"><img style="width:50px;height:50px;" src="http://img03.tbsandbox.com/bao/uploaded/i3/TB10GGKXXXXXXalXXXXXXXXXXXX_!!0-item_pic.jpg_50x50.jpg"><a href="#" class="block-text" style="width:200px;">包邮 正品玛姬儿压缩面膜无纺布纸膜100粒 送泡瓶面膜刷喷瓶 新款</a><span>1</span>
	        </div>
	      </td>
	      <td rowspan="1" class="center" width="11%">56.50</td>
	      <td rowspan="1" class="center" width="13%">
	        <ul class="unstyled">
	          <li>交易成功</li>
	          <li><a href="#">订单详情</a></li>
	          <li><a href="#">对方已评</a></li>
	        </ul>
	      </td>
	      <td rowspan="1" class="center" width="13%"><a href="#" class="btn">评价 </a></td>
	      <td rowspan="1" class="center" width="13%">
	        <ul class="unstyled">
	          <li><a href="#">删除</a></li>
	          <li><a href="#">标记</a></li>
	          <li><a href="#">分享</a></li>
	        </ul>
	      </td>
	    </tr>
	  </tbody>
	</table>
</div>
<!-- end of #content -->