<!-- #content -->
<div id="content">
	<div style="width: 980px;">
		<div class="">
			<h1>
				<ul class="sui-breadcrumb">
					<li><a href="#">商品管理</a></li>
					<li><a href="#">手机详情</a></li>
				</ul>
			</h1>
		</div>
		<ul class="sui-nav nav-tabs nav-large">
			<li class="active"><a data-toggle="tab" href="#demo3">出售中</a></li>
			<li><a data-toggle="tab" href="#code3">仓库中</a></li>
			<li><a data-toggle="tab" href="#doc3">已生成</a></li>
		</ul>

		<div style="margin-top: -10px;" class="sui-form" id="deschide">
			<span class="sui-dropdown dropdown-bordered dropdown-large select">
				<span class="dropdown-inner">
					<a id="select" role="button" href="javascript:void(0);" data-toggle="dropdown" class="dropdown-toggle">
						<input value="" name="ocategory" type="hidden" onchange="oselectfunc(this.value)">
						<i class="caret"></i><span>全部</span>
					</a>
					<ul role="menu" aria-labelledby="drop4" class="sui-dropdown-menu ocategory" name="ocategory" style="max-height: 300px; overflow-y: auto;">
						<li role="presentation" class="active">
							<a role="menuitem" tabindex="-1" href="javascript:void(0);" value="bj">全部</a>
						</li>
					</ul>
				</span>
			</span>
			<div class="input-control control-right">
				<input style="margin-left: 5px; width: 150px;" class="input-fat" type="search" name="search1" id="osearchs1" value="" placeholder="商家编码" data-inline="true" onkeypress="event.keyCode==13?obbsearch():'';">
					<i class="sui-icon icon-touch-magnifier"></i>
			</div>
			<div class="input-control control-right">
				<input style="margin-left: 5px; width: 150px" class="input-fat" type="search" name="search" id="osearchs" value="" placeholder="宝贝关键词" data-inline="true" onkeypress="event.keyCode==13?obbsearch():'';">
				<i class="sui-icon icon-touch-magnifier"></i>
			</div>
			<button style="margin-left: 15px;" class="sui-btn btn-primary btn-large" onclick="obbsearch()">搜索</button>
			<div id="page" style="display: inline-block; float: right;"></div>
		</div>

		<div class="ui-sortable">
			<table class="sui-table table-bordered table-zebra ">
				<thead>
					<tr>
						<th style="width:18px;">
							<div class="center">
								<label class="checkbox-pretty inline checked" data-toggle="checkbox">
								<input type="checkbox" checked="checked"><span contenteditable="true"></span>
								</label>
							</div>
						</th>
						<th style="width: 52px;">主图</th>
						<th style="width: 40%;">标题</th>
						<th></th>
						<th>新的一列</th>
						<th>新的一列</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							<div class="center">
								<label class="checkbox-pretty inline checked" data-toggle="checkbox">
								<input type="checkbox" checked="checked"><span contenteditable="true"></span>
								</label>
							</div>
						</td>
						<td>
							<div class="center">
								<a href=""><img style="margin: 0; height:60px; width:60px;" alt="商品图片" src="http://img03.taobaocdn.com/bao/uploaded/i3/T1DgHZXmNdXXXgMAwT_012514.jpg_60x60.jpg"></a>
		                	</div>
		                </td>
						<td>999</td>
						<td>99999.00</td>
						<td>99999.00</td>
						<td>99999.00</td>
					</tr>
					<tr>
						<td>
							<div class="center">
								<label class="checkbox-pretty inline checked" data-toggle="checkbox">
								<input type="checkbox" checked="checked"><span contenteditable="true"></span>
								</label>
							</div>
						</td>
						<td>9999.00</td>
						<td>999</td>
						<td>99999.00</td>
						<td>99999.00</td>
						<td>99999.00</td>
					</tr>
					<tr>
						<td>
							<div class="center">
								<label class="checkbox-pretty inline checked" data-toggle="checkbox">
								<input type="checkbox" checked="checked"><span contenteditable="true"></span>
								</label>
							</div>
						</td>
						<td>9999.00</td>
						<td>999</td>
						<td>99999.00</td>
						<td>99999.00</td>
						<td>99999.00</td>
					</tr>
					<tr>
						<td>
							<div class="center">
								<label class="checkbox-pretty inline checked" data-toggle="checkbox">
								<input type="checkbox" checked="checked"><span contenteditable="true"></span>
								</label>
							</div>
						</td>
						<td>9999.00</td>
						<td>999</td>
						<td>99999.00</td>
						<td>99999.00</td>
						<td>99999.00</td>
					</tr>
				</tbody>
			</table>
		</div>
		
		<div class="sui-pagination pagination-large center">
			<ul>
				<li class="prev disabled"><a href="#">«上一页</a></li>
				<li class="active"><a href="#">1</a></li>
				<li><a href="#">2</a></li>
				<li><a href="#">3</a></li>
				<li><a href="#">4</a></li>
				<li><a href="#">5</a></li>
				<li class="dotted"><span>...</span></li>
				<li class="next"><a href="#">下一页»</a></li>
			</ul>
			<div><span>共10页&nbsp;</span><span>
			到
			<input class="page-num" type="text"><button class="page-confirm" onclick="alert(1)">确定</button>
			页</span></div>
		</div>

	</div>
	<!-- end of #content -->