<!-- #menu -->
<div id="menu">
	<ul class="nav">
		<!--<li class="first-child">功能菜单</li>-->
		<li class="first-child current">
			<a href="#"><i class="fui-gear"></i><span class="title">自动橱窗设置</span></a>
		</li>
		<li>
			<a href="?a=recommend&amp;type=1"><span class="title">推荐中的宝贝</span><span class="label number">150</span></a>
		</li>
		<li>
			<a href="?a=recommend&amp;type=2"><span class="title">必推荐的宝贝</span><span class="label number">15</span></a>
		</li>
		<li class="last-child">
			<a href="?a=recommend&amp;type=3"><span class="title">不推荐的宝贝</span><span class="label number">8</span></a>
		</li>
	</ul>
</div>
<!-- end of #header -->
