<!DOCTYPE html>
<html>
<head>
<title>Sui</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<link type="text/css" rel="stylesheet" href="<?php echo $this->getStaticUrl();?>/css/myui.css" media="all">
<script type="text/javascript" src="<?php echo $this->getStaticUrl();?>/js/head.load.min.js"></script>
<script type="text/javascript">
  head.js(
    {libs: "<?php echo $this->getStaticUrl();?>/js/dzg_lib.min.js?ver=11"},
    "<?php echo $this->getStaticUrl();?>/js/script.js?ver=1371402062.12312"
  );
</script>

</head>
<body>

<p>文字字体颜色</p>



</body>
</html>