<!DOCTYPE html>
<html>
<head>
<title>Sui</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<link href="http://g.alicdn.com/sj/dpl/1.4.3/css/sui.min.css" rel="stylesheet">
<script type="text/javascript" src="http://g.alicdn.com/sj/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="http://g.alicdn.com/sj/dpl/1.4.3/js/sui.min.js"></script>
</head>
<body>

<p>表单</p>
<form class="sui-form form-horizontal">
  <div class="control-group">
    <label class="control-label v-top"><b style="color: #f00;">*</b> 
      地点：
    </label>
    <div class="controls"><span class="sui-dropdown dropdown-bordered select"><span class="dropdown-inner"><a id="drop4" role="button" data-toggle="dropdown" href="#" class="dropdown-toggle">
            <input value="hz" name="city" type="hidden"><i class="caret"></i><span>杭州</span></a>
          <ul id="menu4" role="menu" aria-labelledby="drop4" class="sui-dropdown-menu">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:void(0);" value="bj">北京</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:void(0);" value="sb">圣彼得堡</a></li>
            <li role="presentation" class="divider"></li>
            <li role="presentation" class="active"><a role="menuitem" tabindex="-1" href="javascript:void(0);" value="hz">杭州</a></li>
          </ul></span></span>
      <div class="sui-msg msg-error msg-clear help-block">
        <div class="msg-con">该项为必填项</div>
        <s class="msg-icon"></s>
      </div>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label v-top"><b style="color: #f00;">*</b> <span style="padding:0 24px 0 0;">主</span>题：</label>
    <div class="controls"><span class="sui-dropdown dropdown-bordered select"><span class="dropdown-inner"><a id="drop4" role="button" data-toggle="dropdown" href="#" class="dropdown-toggle">
            <input value="1" name="zt" type="hidden"><i class="caret"></i><span>吃喝玩乐</span></a>
          <ul id="menu4" role="menu" aria-labelledby="drop4" class="sui-dropdown-menu">
            <li role="presentation" class="active"><a role="menuitem" tabindex="-1" href="javascript:void(0);" value="1">吃喝玩乐</a></li>
          </ul></span></span>
      <input value="" class="input-xlarge" type="text">
      <div class="sui-msg msg-error msg-clear help-block">
        <div class="msg-con">该项为必填项</div>
        <s class="msg-icon"></s>
      </div>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label v-top"><b style="color: #f00;">*</b> <span style="padding:0 24px 0 0;">内</span>容：</label>
    <div class="controls">
      <textarea style="height: 190px;" class="input-xxlarge"></textarea>
      <div style="vertical-align: top;" class="sui-msg msg-tips msg-default">
        <div class="msg-con">
          <p style="margin-bottom: 8px; font-weight: bold;">消息渠道发送字数提示：</p>
          <p>短信：&nbsp;&nbsp;61个汉字为一条短信，超过分多条发送</p>
          <p>旺旺：&nbsp;&nbsp;系统文本对话消息XXXX个汉字</p>
          <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;浮出消息XXXX汉字</p>
          <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Html系统对话消息XXX个汉字</p>
          <p>站内信：XXXX个汉字</p>
        </div>
        <s class="msg-icon"></s>
      </div>
      <div class="sui-msg msg-error msg-clear help-block">
        <div class="msg-con">该项为必填项</div>
        <s class="msg-icon"></s>
      </div>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label"><span style="padding:0 24px 0 0;">链</span> 
      接：
    </label>
    <div class="controls">
      <input value="" class="input-xxlarge" type="text">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label v-top"><b style="color: #f00;">*</b> 
      发送渠道：
    </label>
    <div class="controls">
      <div class="row-fluid">
        <label data-toggle="radio" class="radio-pretty inline checked">
          <input checked="checked" name="qudao" type="radio"><span>商家中心</span>
        </label>
        <label data-toggle="radio" class="radio-pretty inline">
          <input name="qudao" type="radio"><span>旺旺弹窗</span>
        </label>
        <label data-toggle="radio" class="radio-pretty inline">
          <input name="qudao" type="radio"><span>站内信</span>
        </label>
        <div class="sui-msg msg-tips msg-default msg-clear help-block">
          <div class="msg-con">是否向子账号发送消息：
            <label data-toggle="radio" class="radio-pretty inline">
              <input name="zzh" value="1" type="radio"><span>是</span>
            </label>
            <label data-toggle="radio" class="radio-pretty inline checked">
              <input checked="checked" name="zzh" value="0" type="radio"><span>否</span>
            </label>
          </div>
          <s class="msg-icon"></s>
        </div>
      </div>
      <div class="row-fluid">
        <label class="checkbox inline">
          <input name="m1" value="1" checked="" type="checkbox"> 
          短信发送给店长
        </label>
      </div>
      <div class="row-fluid">
        <label class="checkbox inline">
          <input name="m1" value="2" checked="" type="checkbox"> 
          短信发送给电商决策人
        </label>
      </div>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label"><b style="color: #f00;">*</b> 
      审<span style="padding: 0 6px;">核</span>人：
    </label>
    <div class="controls"><span class="sui-dropdown dropdown-bordered select"><span class="dropdown-inner"><a id="drop4" role="button" data-toggle="dropdown" href="#" class="dropdown-toggle">
            <input value="1" name="zt" type="hidden"><i class="caret"></i><span>管理员</span></a>
          <ul id="menu4" role="menu" aria-labelledby="drop4" class="sui-dropdown-menu">
            <li role="presentation" class="active"><a role="menuitem" tabindex="-1" href="javascript:void(0);" value="1">管理员</a></li>
          </ul></span></span></div>
  </div>
  <div class="control-group">
    <label class="control-label"></label>
    <div class="controls">
      <button type="submit" class="sui-btn btn-primary">提交审核</button>
      <button type="reset" class="sui-btn">重置</button>
    </div>
  </div>
</form>

<p>菜单栏-垂直</p>
<h3>垂直</h3>
<ul class="sui-nav nav-tabs nav-primary nav-large tab-vertical">
<li><a>标签一</a></li>
<li class="active"><a href="#">标签二</a></li>
<li><a href="#">标签二</a></li>
</ul>

<h3>复选框</h3>
<label class="checkbox-pretty inline checked">
<input checked="checked" type="checkbox"><span>鸣人</span>
</label>

</body>
</html>